version: "3.1"
# Intended only for local development

volumes:
  database_data:

services:
  db:
    container_name: reddit-inspired-forum-db
    image: postgres:10-alpine
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
